version: '3.7'

services:
  babyrev:
    read_only: true
    tmpfs:
      - /tmp
      - /run
    restart: always
    build:
      context: "./babyrev"
      dockerfile: ./Dockerfile
    deploy:
      replicas: 3
    environment:
      FLAG: "we{00000000-0000-0000-0000-000000000000@demo-flag}"
    ports:
      - "8000:80"
  kvcloud:
    restart: always
    build:
      context: "./kvcloud"
      dockerfile: ./Dockerfile
    ports:
      - "8001:80"
    networks:
      challs:
        ipv4_address: 172.129.1.100
  dont-bf-me:
    read_only: true
    tmpfs:
      - /tmp
      - /run
    restart: always
    build:
      context: "./dont-bf-me"
      dockerfile: ./Dockerfile
    environment:
      PUB_KEY: "6LcS5woaAAAAAHdytfCWrec4YWiuyjhcMnxoKFSN"
      PRIV_KEY: "6LcS5woaAAAAAJ2YV8Q5CjvXPvBTQvWvjWdrKY7i"
      PASSWORD: "YTYyYThkMGMtNDMwMi00ZDZlLTlkZTYtNWY5ZDE2ZWFiZWY3"
      FLAG: "we{00000000-0000-0000-0000-000000000000@demo-flag}"
    deploy:
      replicas: 3
    ports:
      - "8003:80"
  hashtable:
    read_only: true
    tmpfs:
      - /tmp
      - /run
    restart: always
    build:
      context: "./hashtable"
      dockerfile: ./Dockerfile
    environment:
      FLAG: "we{00000000-0000-0000-0000-000000000000@demo-flag}"
      RECAPTCHA_SECRET: "6Leg5ugUAAAAAN2IPVsDWiqG_jR2OzwUH-tbmYwm"
    ports:
      - "8004:8080"
  notebin:
    restart: always
    build:
      context: "./notebin"
      dockerfile: ./Dockerfile
    environment:
      FLAG: "we{00000000-0000-0000-0000-000000000000@demo-flag}"
    ports:
      - "8005:8080"
  wallet:
    read_only: true
    tmpfs:
      - /tmp
      - /run
    restart: always
    build:
      context: "./wallet"
      dockerfile: ./Dockerfile
    ports:
      - "8006:3000"      

networks:
  challs:
    ipam:
      driver: default
      config:
        - subnet: 172.129.0.0/16
